### ISSUE TITLE
A new set of buckets is created in the database every time Janeway starts

### ISSUE THREAD

**Issue by ThomasJClark** [Acstylos/wpi-suite#13]
Whenever Janeway is run, a new workflow and a new set of buckets are created in the database, but never used.  I suspect this causes slower startup times, and might be responsible for buckets sometimes not loading until you clear your db (not sure if that's still happening).

![console](https://cloud.githubusercontent.com/assets/3964980/5417301/eee66764-8205-11e4-89cf-1daa61ba84f0.png)

**Comment by Acstylos** [comment]
I fixed this with a commit to feature/bucketnames

**Comment by ThomasJClark** [comment]
Awesome. Can you fix it in dev?

**Comment by ThomasJClark** [comment]
Actually, if feature/bucketnames is almost ready to merge, it's fine.

**Comment by Acstylos** [comment]
I'm basically done with feature/bucketnames. I don't think I need to add anything else to the feature. But I'm open to suggestions.
