### ISSUE TITLE
No color on tab creates an irregular task shape.

### ISSUE THREAD

**Issue by Tirvanel** [Acstylos/wpi-suite#14]
When I have a task that doesn't have any colors assigned to it, the box that usually contains the color spills off the top edge of the task rectangle, as seen in the attached picture.
![bug for colors](https://cloud.githubusercontent.com/assets/9456025/5421536/8fef7254-8233-11e4-8ceb-16a12fe0c6d0.png)

**Comment by Acstylos** [comment]
a fix for this has been pushed to hotfix/colorsfix for review
