### ISSUE TITLE
Minitaskviews  layout moves around with colors merged in

### ISSUE THREAD

**Issue by ThomasJClark** [Acstylos/wpi-suite#16]
The icon and tile move into the wrong position when the Minitaskview is collapsed, and the the color 
rectangle changes shape.

**Before colors:**
![minitaskview](https://cloud.githubusercontent.com/assets/3964980/5421662/dbd95dfe-8235-11e4-8210-b15f17b1a7df.gif)

**After colors:**
![minitaskview](https://cloud.githubusercontent.com/assets/3964980/5421632/584cfa18-8235-11e4-8674-90173b5340e7.gif)

**Comment by Acstylos** [comment]
a fix for this has been pushed to hotfix/colorsfix for review
