### ISSUE TITLE
feature/bucketnames - It's possible to accidently permanantly remove the name of a stage

### ISSUE THREAD

**Issue by ThomasJClark** [Acstylos/wpi-suite#17]
There's no validation to require you to have something in the name of the stage.  Combined with the facts that the default value of the textbox is empty and there is no "cancel" button, it's pretty easy for a user to try to cancel renaming and end up with no stage name, which cannot be fixed, since it's no loner possible to click on the stage name.

![rename-bucket](https://cloud.githubusercontent.com/assets/3964980/5426804/bf49f982-833e-11e4-974b-e48e954427ec.gif)

IMO we should not allow blank stage names, and the default value (not just the hint) of the textbox should be the current stage name.

**Comment by Acstylos** [comment]
Fix for this issue has been pushed for review.
