### ISSUE TITLE
Tasks no longer show up Branch: feature/requirements

### ISSUE THREAD

**Issue by lambertwang-zz** [Acstylos/wpi-suite#5]
I closed Janeway and opened it again.
All my tasks disappeared.
My tasks save to the database but just don't display.
Whoever added the user stuff could probably fix it because I copied most of their code for the requirements.

**Comment by lambertwang-zz** [comment]
Reset database and fixed the issue.
New issue: Requirements aren't persisting in tasks

**Comment by willwen** [comment]
I know sam and Mike also have that problem. We get it to work SOMETIMES, but just restarting server and logging in..

**Comment by Jccrespi** [comment]
Cleaning will also solve this issue

**Comment by lambertwang-zz** [comment]
Fixed last night. The problem involved setting the dimensions of the miniview to 0.
