### ISSUE TITLE
View Requirement button fail when requirement manager isn't loaded

### ISSUE THREAD

**Issue by codermaxzhou** [Acstylos/wpi-suite#8]
Once the Janeway opened, if you don't open the requirement manager tab, the requirement button will fail to open requirements. Only if you open the requirement tab, the requirement button will work.

**Comment by lambertwang-zz** [comment]
Fixed and merged to requirements branch

**Comment by lambertwang-zz** [comment]
It's been merged to dev. Please close this issue.
